### ISSUE TITLE
Contacter Samuel Tallet

### ISSUE THREAD

**Issue by Ffredout** [SamuelTallet/SketchUp-Parametric-Modeling-Plugin#2]
Bonjour,
Je ne suis pas très à l'aise avec l'interface GitHub, mais c'est le seul moyen que j'ai trouvé pour contacter Samuel Tallet. Je voudrais lui envoyer un mail pour parler d'un projet commun.

**Comment by SamuelTallet** [comment]
Bonjour Frédéric,
Je vous ai envoyé un mail.
